# Time comparison

In [13]:
import time
import numpy as np
start =time.time()
l=[x*x for x in range(10)]
print(l)
end = time.time()
print('time with lists:',end-start)
start =time.time()
a=np.arange(10000)
a=a*a
end = time.time()
print('time with np arrays:',end-start)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
time with lists: 0.0009953975677490234
time with np arrays: 0.0009982585906982422


# Trignometric functions

In [2]:
import numpy as np
a=np.random.randint(100,size=23)
np.sin(a)

array([-0.42818267, -0.53657292, -0.8462204 , -0.95892427, -0.99388865,
       -0.99920683,  0.96379539,  0.90178835, -0.62988799, -0.66363388,
        0.31322878,  0.99060736, -0.94828214, -0.24525199, -0.96611777,
       -0.91652155,  0.14112001,  0.01770193,  0.39592515, -0.26237485,
       -0.83177474,  0.99060736,  0.99952016])

In [3]:
np.sin(3.14/2)                   #must be in radain values

0.9999996829318346

In [4]:
np.arcsin(1)

1.5707963267948966

In [5]:
np.rad2deg(1.5707963267948966)

90.0

# Log and exponential functions

In [6]:
print(np.log(2))
print(np.log(1))
print(np.log(np.exp(1)))

0.6931471805599453
0.0
1.0


In [7]:
print(np.log2(2))
print(np.log2(32))

1.0
5.0


In [8]:
np.log(0)

C:\Users\Vikki\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [9]:
np.log1p(2)
#np.log1p(x)= np.log(1+x)

1.0986122886681098

In [10]:
np.log(2+1)

1.0986122886681098

In [11]:
print(np.exp(1))     #power terms

2.718281828459045


In [16]:
print(np.exp2(2))

4.0


In [19]:
print(np.expm1(5))
print(np.exp(5)-1)   #np.expm(x)= np.exp(x)-1

147.4131591025766
147.4131591025766


In [18]:
print(np.exp(5))

148.4131591025766


# Statastics

In [20]:
a=np.random.randint(100,size=5)
a

array([72, 85, 46, 68, 82])

In [22]:
print(a.sum())
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print()


353
353
70.6
72.0
13.792751719653335



In [24]:
np.sort(a)

array([46, 68, 72, 82, 85])

In [25]:
print(np.quantile(a,0.25))
print(np.quantile(a,0.5))
print(np.quantile(a,0.75))
print(np.quantile(a,1))

68.0
72.0
82.0
85.0


# Broadcasting

In [29]:
a=np.arange(5)
b=np.arange(4)
a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [33]:
a=np.arange(10).reshape(5,2)
print(a)
b=np.arange(2)
print(b)
a+b

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1]


array([[ 0,  2],
       [ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [34]:
a=np.arange(15).reshape(5,2)
b=np.arange(5)

a+b

ValueError: cannot reshape array of size 15 into shape (5,2)

In [39]:
a=np.arange(15).reshape(5,3,1)
print(a)
b=np.arange(5)
print(b)
a+b

[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]]]
[0 1 2 3 4]


array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6]],

       [[ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9]],

       [[ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12]],

       [[ 9, 10, 11, 12, 13],
        [10, 11, 12, 13, 14],
        [11, 12, 13, 14, 15]],

       [[12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18]]])

In [41]:
a=np.arange(15).reshape(5,3)
print(a)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
105
[30 35 40]
[ 3 12 21 30 39]


In [42]:
np.random.seed(5)
a=np.random.randint(50,size=10)
b=np.random.randint(50,size=10)
print(a)
print(b)

[35 14 47 38 16  9  8 36 39 27]
[48 30 16  7 12 15 49 39 16 27]


In [43]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or 1-d array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



In [44]:
def maxnumber(n1,n2):
    if n1>n2:
        return n1
    else:
        return n2
maxnumber(5,44)

44

In [47]:
maxnumber_vec=np.vectorize(maxnumber)
maxnumber_vec(a,b)

array([48, 30, 47, 38, 16, 15, 49, 39, 39, 27])

# Stacking Arrays

In [50]:
a = np.arange(6)
b=np.arange(6)
np.hstack([a,b])

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [51]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [54]:
a = np.arange(6).reshape(2,3)
b=np.arange(6).reshape(2,3)
np.hstack([a,b])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [56]:
a = np.arange(6).reshape(2,3)
b=np.arange(3)
np.vstack([a,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

# Linear algebra

In [57]:
np.linalg.det(np.eye(2))

1.0

In [59]:
np.linalg.det(np.array([[1,2],[5,7]]))

-2.999999999999999

In [60]:
np.linalg.inv(np.array([[1,2],[5,7]]))

array([[-2.33333333,  0.66666667],
       [ 1.66666667, -0.33333333]])

In [61]:
np.linalg.matrix_rank(np.array([[1,2],[5,7]]))

2

- np.dot
- np.matmul

In [6]:
import datetime
file=open('data.txt')
data=file.read()
data=eval(data)
data

[{'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 520},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 521},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 523},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 524},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 530},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 531},
 {'attendance': 'A',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 533},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 534},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
 

In [2]:
import datetime
file=open('dates.txt')
dates=file.read()
dates=eval(dates)
dates

[457,
 459,
 460,
 461,
 462,
 463,
 464,
 466,
 467,
 468,
 469,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 480,
 482,
 484,
 485,
 486,
 487,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 515,
 516,
 517,
 518,
 520,
 521,
 523,
 524,
 530,
 531,
 533,
 534,
 535,
 536,
 539,
 540,
 541,
 544,
 546,
 549,
 550,
 551,
 552,
 555,
 556,
 557,
 558,
 560,
 561,
 564,
 565,
 568,
 569,
 572,
 574,
 575,
 576,
 578,
 579,
 580,
 774,
 775,
 776,
 777,
 778,
 781,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 791,
 792,
 793,
 795,
 796,
 797,
 798,
 800,
 803,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 904,
 905,
 906,
 908,
 909,
 911,
 912,
 914,
 915,
 917,
 918,
 919,
 921,
 923,
 924,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935

In [4]:
data[1]

{'attendance': 'P',
 'session': 'FN',
 'date': datetime.date(2019, 12, 21),
 'level': 3,
 'student_id': 521}

In [7]:
type(data)

list

In [8]:
len(data)

2176

In [11]:
key=lambda i:(i['student_id'],i[data],i['session'])
key

<function __main__.<lambda>(i)>

In [9]:
sdata=sorted(data,key=lambda i:(i['student_id'],i['date'],i['session']))
od={}
for i in sdata:
    if i['student_id'] in od:
        od[i['student_id']].append(i['attendance'])
    else:
        od[i['student_id']]=[]
        od[i['student_id']].append(i['attendance'])
l=[]
for i in od:
    temp={}
    temp['student_id']=i
    temp['attendance']=od[i]
    l.append(temp)
for i in l:
    print(i)
        

{'student_id': 457, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 459, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 460, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 461, 'attendance': ['P', 'A', 'P', 'P', 'P', 'P']}
{'student_id': 462, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 463, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 464, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 466, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 467, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 468, 'attendance': ['A', 'A', 'P', 'P', 'A', 'P']}
{'student_id': 469, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 471, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 472, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 473, 'attendance': ['P', 'P', 'P', 'P', 'A', 'P']}
{'student_id': 474, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_