In [1]:
import numpy
numpy.__file__

'C:\\Users\\Vikki\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'

In [3]:
numpy.array([1,2,3])

array([1, 2, 3])

In [5]:
import numpy as np
np.__version__

'1.16.5'

In [ ]:
from numpy import *  #all the modules and subpackages will be imported

#  Numpy array creation from

- list
- tuple
- range

In [6]:
np.array([34,23,56])

array([34, 23, 56])

In [7]:
np.array((1,2,3))

array([1, 2, 3])

In [8]:
np.array(range(5,10))

array([5, 6, 7, 8, 9])

In [9]:
a = np.array(range(5,10))
print(a)
print(type(a))

[5 6 7 8 9]
<class 'numpy.ndarray'>


In [14]:
print(a)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)  #no of bytes for eacch items
print(a.ndim)
print(a.nbytes)    # array size in bytes


[5 6 7 8 9]
(5,)
5
int32
4
1
20


In [13]:
l=[1]
t=(1,)
print(type(l),type(t))

<class 'list'> <class 'tuple'>


In [15]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
print(a2)
print(a2.shape)
print(a2.size)
print(a2.dtype)
print(a2.itemsize) 
print(a2.ndim)
print(a2.nbytes) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int32
4
2
36


In [19]:
print(a2.shape[1])

3


In [25]:
a=np.array([1,2,3],dtype=np.int8)
print(a)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)  #no of bytes for eacch items
print(a.ndim)
print(a.nbytes)    # array size in bytes


[1 2 3]
(3,)
3
int8
1
1
3


In [26]:
a=np.array([1,2,3,(2**32)+1])
print(a.dtype)

int64


In [33]:
a=np.array([1,2,3,65])
print(a.dtype)

int32


In [31]:
a = np.array([1,2,3,'czc'])
print(a.dtype)
a = np.array([1,2,3,None])
print(a.dtype)
a = np.array([1,2,3,np.nan])
print(a.dtype)

<U11
object
float64


# Intializing arrays

- zeros 
- ones
- full
- eye
- diag

In [34]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [35]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.ones((2,3),bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [37]:
np.ones((2,3,bool)

SyntaxError: unexpected EOF while parsing (<ipython-input-37-749d6dbfe351>, line 1)

In [44]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.full((2,3),3)

array([[3, 3, 3],
       [3, 3, 3]])

In [49]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

In [54]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [57]:
a=np.arange(5)
b=np.ones(5)
c=np.zeros(5)
print(a)
print(b)
print(c)

[0 1 2 3 4]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


In [60]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)


[1. 2. 3. 4. 5.]
[-1.  0.  1.  2.  3.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 0. 0. 0. 0.]
[0. 1. 2. 3. 4.]


In [59]:
print(a*2)
print(a**2)
print(a+2)
print(a-2)
print(a/2)

[0 2 4 6 8]
[ 0  1  4  9 16]
[2 3 4 5 6]
[-2 -1  0  1  2]
[0.  0.5 1.  1.5 2. ]


# creating arrays in range

- arange
- linspace

In [42]:
print(np.arange(5))
print(np.arange(10,100,5))
print(np.arange(5,10,0.5))


[0 1 2 3 4]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [43]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

# Random

In [63]:
np.random.randint(100)

13

In [64]:
np.random.randint(100,size=5)

array([ 5, 43, 56, 36, 80])

In [67]:
np.random.randint(100,size=(5,2))

array([[57, 49],
       [73, 77],
       [33,  9],
       [43, 77],
       [65, 72]])

In [68]:
np.random.randint(50,100,size=(5,2))

array([[96, 92],
       [63, 65],
       [74, 70],
       [61, 82],
       [97, 94]])

In [71]:
np.random.random(100)

array([0.89610176, 0.92896847, 0.44450809, 0.4133134 , 0.9021612 ,
       0.8731151 , 0.67128677, 0.95473672, 0.13544603, 0.32477504,
       0.21641665, 0.8828221 , 0.46724873, 0.32410859, 0.73221169,
       0.21850526, 0.27397023, 0.56418472, 0.16620651, 0.40814424,
       0.02220561, 0.80132576, 0.90690088, 0.02882671, 0.63602294,
       0.86320117, 0.80032728, 0.61622619, 0.66036137, 0.9337894 ,
       0.67924884, 0.30887771, 0.52020617, 0.50559179, 0.54362079,
       0.94049208, 0.04539041, 0.42168746, 0.64375584, 0.47704967,
       0.12092568, 0.0793911 , 0.67017638, 0.24978163, 0.8963253 ,
       0.07657354, 0.36782374, 0.29905758, 0.06657133, 0.54621391,
       0.01755218, 0.23888428, 0.63504245, 0.07133216, 0.68293105,
       0.9320737 , 0.48074928, 0.51808095, 0.47729658, 0.54950641,
       0.8037812 , 0.86595841, 0.88406371, 0.23141486, 0.8661534 ,
       0.45267415, 0.5604545 , 0.25756226, 0.28653854, 0.51594543,
       0.67270489, 0.3437457 , 0.20696128, 0.3003411 , 0.55766

In [72]:
np.random.rand()

0.008454621279404106

In [73]:
np.random.rand(5)

array([0.83314773, 0.14390686, 0.74446379, 0.6904325 , 0.06121636])

In [74]:
np.random.rand(5,2)

array([[0.4428508 , 0.48519228],
       [0.89353574, 0.65861389],
       [0.07449779, 0.22395278],
       [0.86806575, 0.87208677],
       [0.58820628, 0.19087546]])

In [75]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [78]:
r=np.arange(10,20)
np.random.shuffle(r)
print(r)

[11 16 19 12 17 13 14 10 15 18]


# Array Manipulation

In [90]:
a=np.arange(20)
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [91]:
help(np.resize)

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Notes
    -----
    i.e. it does not apply interpolation/extrapolation.
    It fills the return array with the required 

In [92]:
np.resize(a,(13,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [93]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [95]:
z=np.arange(20)
z.resize(13,2)
print(z)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [ 0  0]
 [ 0  0]
 [ 0  0]]


In [97]:
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

In [99]:
np.expand_dims(a,0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [106]:
a2=np.arange(9).reshape(3,3)
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
np.expand_dims(a2,1)

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [108]:
np.expand_dims(a2,1).shape

(3, 1, 3)

In [111]:
np.expand_dims(a2,0).shape

(1, 3, 3)